/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package DataEntry;

import java.sql.*;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import java.text.MessageFormat;



/**
 *
 * @author apost
 */
public class DataEntry extends javax.swing.JFrame {
    
    
    
   

    /**
     * Creates new form DataEntry
     */
    public DataEntry() {
        
        initComponents();
      
    }

    private PreparedStatement setString(int i, String text) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
public class connection {
    // Specify the URL of the database. The format of the URL is [protocol]:[subprotocol]:[server:port/databaseName]
    private static final String DB_URL = "jdbc:mysql://localhost:3306/up1072507_2";
    public static void main(String[] args){
// try-with-resources
        try (
// Step 1: Connect to database ("root" and "" are the default username and password for XAMPP)
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/up1072507_2", "root", "Apostolos2001");
// Step 2: Initialize a Statement object for executing queries to database
                Statement stmt = con.createStatement();
// Step 3: Execute query and get results
                ResultSet resultSet = stmt.executeQuery("SELECT * FROM customer");) {
// Step 4: Process and print results
            ResultSetMetaData metaData = resultSet.getMetaData();
            int numberOfColumns = metaData.getColumnCount();
// Print column names
            for (int i = 1; i <= numberOfColumns; i++)
                System.out.printf("%-8s\t", metaData.getColumnName(i));
            System.out.println();
// Move cursor to the next row of the results and print the value of each column
            while (resultSet.next()){
                for (int i = 1; i <= numberOfColumns; i++)
                    System.out.printf("%-8s\t", resultSet.getObject(i));
                System.out.println();
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtxCustomer = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtxtFirstName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtxtAdress = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtxtCreateDate = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jtxtLastName = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jtxtActive = new javax.swing.JTextField();
        jtxtLastName1 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jbtnExit = new javax.swing.JButton();
        jbtUpdate = new javax.swing.JButton();
        jbtnReset = new javax.swing.JButton();
        jbtnPrint = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "customer_id", "first_name", "email", "address_id", "active", "create_date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1420, 530));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 1440, 480));

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Customer_id");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 110, 30));

        jtxCustomer.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jtxCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxCustomerActionPerformed(evt);
            }
        });
        jPanel2.add(jtxCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 200, 40));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("First Name");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 110, 40));

        jtxtFirstName.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jtxtFirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtFirstNameActionPerformed(evt);
            }
        });
        jPanel2.add(jtxtFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 200, 40));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Address_id");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 10, 90, 50));

        jtxtAdress.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jtxtAdress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtAdressActionPerformed(evt);
            }
        });
        jPanel2.add(jtxtAdress, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 20, 200, 40));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Active");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 70, 70, 50));

        jtxtCreateDate.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jPanel2.add(jtxtCreateDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 150, 200, 40));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Last Name");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 30, -1, -1));

        jtxtLastName.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jtxtLastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtLastNameActionPerformed(evt);
            }
        });
        jPanel2.add(jtxtLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 20, 200, 40));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Email");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 80, 50, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("create_date");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 150, -1, -1));

        jtxtActive.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jPanel2.add(jtxtActive, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 90, 200, 40));

        jtxtLastName1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jtxtLastName1.setText("jTextField1");
        jtxtLastName1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtLastName1ActionPerformed(evt);
            }
        });
        jPanel2.add(jtxtLastName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 20, 200, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1440, 210));

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtnExit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnExit.setText("Exit");
        jbtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnExitActionPerformed(evt);
            }
        });
        jPanel3.add(jbtnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 20, 140, 40));

        jbtUpdate.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtUpdate.setText("Update");
        jbtUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtUpdateActionPerformed(evt);
            }
        });
        jPanel3.add(jbtUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 140, 40));

        jbtnReset.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnReset.setText("Reset");
        jbtnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnResetActionPerformed(evt);
            }
        });
        jPanel3.add(jbtnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 20, 140, 40));

        jbtnPrint.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnPrint.setText("Print");
        jbtnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPrintActionPerformed(evt);
            }
        });
        jPanel3.add(jbtnPrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 20, 140, 40));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 1440, 80));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

   

   
    
    private JFrame frame ;
 
    private void jbtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnExitActionPerformed
        
        frame = new JFrame ("Exit");
        if(JOptionPane.showConfirmDialog(frame,"Confirm if you want to Exit","Data Entry Form",
                JOptionPane.YES_NO_OPTION )==JOptionPane.YES_NO_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_jbtnExitActionPerformed

    private void jbtnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPrintActionPerformed
        MessageFormat header =new MessageFormat("Printing in Progress");
        MessageFormat footer =new MessageFormat("Page({0,number,integer}");
        
        try{
            jTable1.print(JTable.PrintMode.NORMAL,header,footer); 
        }
        catch (java.awt.print.PrinterException e){
            System.err.format("No Printer found", e.getMessage() );
        }
        
    }//GEN-LAST:event_jbtnPrintActionPerformed

    private void jbtnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnResetActionPerformed
        try{
            jtxCustomer.setText(null);
            jtxtFirstName.setText(null);
            jtxtLastName.setText(null);
            jtxtAdress.setText(null);
            jtxtActive.setText(null);
            jtxtCreateDate.setText(null);
            
            
        }
        catch (Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jbtnResetActionPerformed

    private void jtxCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxCustomerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxCustomerActionPerformed

    private void jtxtLastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtLastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtLastNameActionPerformed

    private void jtxtAdressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtAdressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtAdressActionPerformed

    private void jtxtLastName1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtLastName1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtLastName1ActionPerformed

    private void jbtUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtUpdateActionPerformed
  PreparedStatement ps;
        ResultSet rs;
        String sql = "update customer set first_name = ?, last_name = ?, address_id=?, active=?, create_date=? where customer_id = ?";
        String fn = jtxtFirstName.getText();
        String ln = jtxtLastName.getText();
        String id = jtxCustomer.getText();
        String ad = jtxtAdress.getText();
        String ac =jtxtActive.getText();
        String cd =jtxtCreateDate.getText();
        
        try{
            java.sql.Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/up1072507_2", "root", "Apostolos2001");
            ps = con.prepareStatement(sql);
            ps.setString(1,fn);
            ps.setString(2,ln);
            ps.setString(3,id);
            ps.setString(4, ad);
            ps.setString(5, ac);
            ps.setString(6, cd);
            
            
            rs = ps.executeQuery();
            JOptionPane.showMessageDialog(null, "System Update");
            
        }
        catch(SQLException e){
        System.out.println(""+e);
        }
    }//GEN-LAST:event_jbtUpdateActionPerformed

    private void jtxtFirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtFirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtFirstNameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DataEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DataEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DataEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DataEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DataEntry().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbtUpdate;
    private javax.swing.JButton jbtnExit;
    private javax.swing.JButton jbtnPrint;
    private javax.swing.JButton jbtnReset;
    private javax.swing.JTextField jtxCustomer;
    private javax.swing.JTextField jtxtActive;
    private javax.swing.JTextField jtxtAdress;
    private javax.swing.JTextField jtxtCreateDate;
    private javax.swing.JTextField jtxtFirstName;
    private javax.swing.JTextField jtxtLastName;
    private javax.swing.JTextField jtxtLastName1;
    // End of variables declaration//GEN-END:variables
}
